name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - Prod

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22

          script: |
            set -e

            cd /home/ubuntu/Docker_project

            echo "Pull latest code"
            git fetch origin
            git reset --hard origin/Prod

            echo "Stop and remove old containers"
            docker compose down --remove-orphans

            echo "Remove old images"
            docker image prune -af

            echo "Build new image"
            docker compose build --no-cache

            echo "Start new containers"
            docker compose up -d

            echo "Deployment Successful"

            docker compose ps
